CREATE TABLE arenas
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_arenas PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    court_id BIGINT                                  NOT NULL,
    start_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE court
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    sport    VARCHAR(255)                            NOT NULL,
    arena_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_court PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE bookings
    ADD CONSTRAINT uc_cfeff974d23ab051b7d0f4026 UNIQUE (court_id, start_at, end_at);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_COURT FOREIGN KEY (court_id) REFERENCES court (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE court
    ADD CONSTRAINT FK_COURT_ON_ARENA FOREIGN KEY (arena_id) REFERENCES arenas (id);